insert into cookie(id,name) values(1,'Chocolate Chips');
insert into cookie(id,name) values(2,'Peanut butter cookies');
insert into cookie(id,name) values(3,'Oatmeal raisin cookies');
insert into cookie(id,name) values(4,'Shortbread cookies');
insert into cookie(id,name) values(5,'Gingerbread cookies');
insert into cookie(id,name) values(6,'Sugar cookies');
insert into cookie(id,name) values(7,'Black and white cookies');
insert into cookie(id,name) values(8,'Butter cookies');
insert into cookie(id,name) values(9,'Snickerdoodle cookies');
insert into cookie(id,name) values(10,'White chocolate macadamia nut cookies');
insert into cookie(id,name) values(11,'Biscotti');
insert into cookie(id,name) values(12,'Gingersnaps');
insert into cookie(id,name) values(13,'Peanut Butter Blossoms');
insert into cookie(id,name) values(14,'Macarons');
insert into cookie(id,name) values(15,'TerroLex{c0n6r47z_y0u_d1d_17!}');
insert into cookie(id,name) values(16,'Macaroons');
insert into cookie(id,name) values(17,'Macaroons');
insert into cookie(id,name) values(18,'Butter Pecan Cookies');
insert into cookie(id,name) values(19,'Crinkle Cookies');
insert into cookie(id,name) values(20,'Whoopie Pies');
insert into cookie(id,name) values(21,'Molasses Cookies');
insert into cookie(id,name) values(22,'Hamantaschen');
insert into cookie(id,name) values(23,'Icebox cookies');
insert into cookie(id,name) values(24,'Lofthouse cookies');
insert into cookie(id,name) values(25,'Meringue cookies');